const mongoose = require('mongoose')
// Ensure the Category model is processed by Mongoose (for populating Menu Item queries)
require('./category')
const decorItemSchema = require('./decorItemSchema')
module.exports = mongoose.model('DecorItem', decorItemSchema)